version: "3"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    expose:
      - "2181"
    depends_on:
      - kafka
  kafka:
    image: wurstmeister/kafka:2.11-1.1.1
    expose:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: custom-topic-1:1:1,custom-topic-2:1:1
  mongo:
    image: mongo
  test:
    build: .
    depends_on:
      - kafka
      - mongo